// Copyright 2026 The gputop Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated from NVIDIA's Xid catalog (https://docs.nvidia.com/deploy/xid-errors/Xid-Catalog.xlsx,
// retrieved 2026-09-15). DO NOT EDIT by hand; regenerate from the catalog.

package nvidia

// XIDInfo is one entry of NVIDIA's Xid catalog.
type XIDInfo struct {
	Mnemonic    string
	Description string
	// Action is the catalog's "Resolution Bucket (Immediate Action)".
	Action string
}

// xidCatalog maps Xid codes to catalog entries.
var xidCatalog = map[uint64]XIDInfo{
	8:   {"ROBUST_CHANNEL_FIFO_ERROR_IDLE_TIMEOUT", "GPU stopped processing", "RESTART_APP"},
	11:  {"ROBUST_CHANNEL_GR_ERROR_MISSING_HW", "Invalid or corrupted push buffer stream", "RESTART_APP"},
	13:  {"ROBUST_CHANNEL_GR_EXCEPTION / ROBUST_CHANNEL_GR_ERROR_SW_NOTIFY", "Graphics Engine Exception", "RESTART_APP"},
	25:  {"ROBUST_CHANNEL_GR_ILLEGAL_NOTIFY", "Invalid or illegal push buffer stream", "RESTART_APP"},
	31:  {"ROBUST_CHANNEL_FIFO_ERROR_MMU_ERR_FLT", "GPU memory page fault", "RESTART_APP"},
	32:  {"ROBUST_CHANNEL_PBDMA_ERROR", "Invalid or corrupted push buffer stream", "RESTART_APP"},
	37:  {"ROBUST_CHANNEL_FECS_ERR_UNIMP_FIRMWARE_METHOD", "Driver firmware error", "IGNORE"},
	38:  {"ROBUST_CHANNEL_FECS_ERR_WATCHDOG_TIMEOUT", "Driver firmware error", "IGNORE"},
	39:  {"ROBUST_CHANNEL_CE0_ERROR", "Copy Engine Exception", "RESTART_APP"},
	40:  {"ROBUST_CHANNEL_CE1_ERROR", "Copy Engine Exception", "RESTART_APP"},
	41:  {"ROBUST_CHANNEL_CE2_ERROR", "Copy Engine Exception", "RESTART_APP"},
	43:  {"ROBUST_CHANNEL_RESETCHANNEL_VERIF_ERROR", "GPU stopped processing", "IGNORE"},
	44:  {"ROBUST_CHANNEL_GR_FAULT_DURING_CTXSW", "Graphics Engine fault during context switch", "IGNORE"},
	45:  {"ROBUST_CHANNEL_PREEMPTIVE_REMOVAL", "Preemptive cleanup, due to previous errors", "WORKFLOW_XID_45"},
	46:  {"ROBUST_CHANNEL_GPU_TIMEOUT_ERROR", "GPU stopped processing", "RESET_GPU"},
	48:  {"ROBUST_CHANNEL_GPU_ECC_DBE", "Double Bit ECC Error", "WORKFLOW_XID_48"},
	54:  {"SILENT_RUNNING_PWR_REDUCED_CLOCKING", "Auxiliary power is not connected to the GPU board", "CHECK_MECHANICALS"},
	60:  {"ROBUST_CHANNEL_SEC2_ERROR", "Video processor exception", "RESTART_APP"},
	62:  {"PMU_HALT_ERROR", "Internal micro-controller halt (newer drivers)", "RESET_GPU"},
	63:  {"INFOROM_DRAM_RETIREMENT_EVENT", "GPU memory remapping event", "IGNORE"},
	64:  {"INFOROM_DRAM_RETIREMENT_FAILURE", "GPU memory remapping failure", "RESET_GPU"},
	66:  {"ROBUST_CHANNEL_FECS_ERR_REG_ACCESS_VIOLATION", "Illegal access by driver", "IGNORE"},
	67:  {"ROBUST_CHANNEL_FECS_ERR_VERIF_VIOLATION", "Illegal access by driver", "IGNORE"},
	68:  {"ROBUST_CHANNEL_NVDEC0_ERROR", "NVDEC0 Exception", "RESTART_APP"},
	69:  {"ROBUST_CHANNEL_GR_CLASS_ERROR", "Graphics Engine class error", "RESTART_APP"},
	70:  {"ROBUST_CHANNEL_CE3_ERROR", "CE3: Unknown Error", "RESTART_APP"},
	71:  {"ROBUST_CHANNEL_CE4_ERROR", "CE4: Unknown Error", "RESTART_APP"},
	72:  {"ROBUST_CHANNEL_CE5_ERROR", "CE5: Unknown Error", "RESTART_APP"},
	74:  {"NVLINK_ERROR", "NVLINK Error", "WORKFLOW_NVLINK_ERR"},
	75:  {"ROBUST_CHANNEL_CE6_ERROR", "CE6: Unknown Error", "RESTART_APP"},
	76:  {"ROBUST_CHANNEL_CE7_ERROR", "CE7: Unknown Error", "RESTART_APP"},
	77:  {"ROBUST_CHANNEL_CE8_ERROR", "CE8: Unknown Error", "RESTART_APP"},
	78:  {"VGPU_START_ERROR", "vGPU Start Error", "UPDATE_SWFW"},
	79:  {"ROBUST_CHANNEL_GPU_HAS_FALLEN_OFF_THE_BUS", "GPU has fallen off the bus", "RESTART_BM"},
	80:  {"PBDMA_PUSHBUFFER_CRC_MISMATCH", "Corrupted data sent to GPU", "RESTART_APP"},
	82:  {"ROBUST_CHANNEL_NVJPG0_ERROR", "NVJPG0 Error", "RESTART_APP"},
	83:  {"ROBUST_CHANNEL_NVDEC1_ERROR", "NVDEC1 Error", "RESTART_APP"},
	84:  {"ROBUST_CHANNEL_NVDEC2_ERROR", "NVDEC2 Error", "RESTART_APP"},
	85:  {"ROBUST_CHANNEL_CE9_ERROR", "CE9: Unknown Error", "RESTART_APP"},
	86:  {"ROBUST_CHANNEL_OFA0_ERROR", "OFA Exception", "RESTART_APP"},
	88:  {"ROBUST_CHANNEL_NVDEC3_ERROR", "NVDEC3 Error", "RESTART_APP"},
	89:  {"ROBUST_CHANNEL_NVDEC4_ERROR", "NVDEC4 Error", "RESTART_APP"},
	92:  {"EXCESSIVE_SBE_INTERRUPTS", "High single-bit ECC error rate", "IGNORE"},
	93:  {"INFOROM_ERASE_LIMIT_EXCEEDED", "Non-fatal violation of provisioned InfoROM wear limit", "IGNORE"},
	94:  {"ROBUST_CHANNEL_CONTAINED_ERROR", "Contained memory error", "RESTART_APP"},
	95:  {"ROBUST_CHANNEL_UNCONTAINED_ERROR", "Uncontained memory error", "RESET_GPU"},
	96:  {"ROBUST_CHANNEL_NVDEC5_ERROR", "NVDEC5 Error", "RESTART_APP"},
	97:  {"ROBUST_CHANNEL_NVDEC6_ERROR", "NVDEC6 Error", "RESTART_APP"},
	98:  {"ROBUST_CHANNEL_NVDEC7_ERROR", "NVDEC7 Error", "RESTART_APP"},
	99:  {"ROBUST_CHANNEL_NVJPG1_ERROR", "NVJPG1 Error", "RESTART_APP"},
	100: {"ROBUST_CHANNEL_NVJPG2_ERROR", "NVJPG2 Error", "RESTART_APP"},
	101: {"ROBUST_CHANNEL_NVJPG3_ERROR", "NVJPG3 Error", "RESTART_APP"},
	102: {"ROBUST_CHANNEL_NVJPG4_ERROR", "NVJPG4 Error", "RESTART_APP"},
	103: {"ROBUST_CHANNEL_NVJPG5_ERROR", "NVJPG5 Error", "RESTART_APP"},
	104: {"ROBUST_CHANNEL_NVJPG6_ERROR", "NVJPG6 Error", "RESTART_APP"},
	105: {"ROBUST_CHANNEL_NVJPG7_ERROR", "NVJPG7 Error", "RESTART_APP"},
	106: {"SMBPBI_TEST_MESSAGE", "SMBPBI Test Message", "IGNORE"},
	107: {"SMBPBI_TEST_MESSAGE_SILENT", "SMBPBI Test Message Silent", "IGNORE"},
	109: {"ROBUST_CHANNEL_CTXSW_TIMEOUT_ERROR", "Context Switch Timeout Error", "RESET_GPU"},
	110: {"SEC_FAULT_ERROR", "Security Fault Error", "RESET_GPU"},
	119: {"GSP_RPC_TIMEOUT", "GSP RPC Timeout", "RESET_GPU"},
	120: {"GSP_ERROR", "GSP Error", "RESET_GPU"},
	121: {"C2C_ERROR", "C2C Error", "IGNORE"},
	126: {"ROBUST_CHANNEL_CE10_ERROR", "CE10: Unknown Error", "RESTART_APP"},
	127: {"ROBUST_CHANNEL_CE11_ERROR", "CE11: Unknown Error", "RESTART_APP"},
	128: {"ROBUST_CHANNEL_CE12_ERROR", "CE12: Unknown Error", "RESTART_APP"},
	129: {"ROBUST_CHANNEL_CE13_ERROR", "CE13: Unknown Error", "RESTART_APP"},
	130: {"ROBUST_CHANNEL_CE14_ERROR", "CE14: Unknown Error", "RESTART_APP"},
	131: {"ROBUST_CHANNEL_CE15_ERROR", "CE15: Unknown Error", "RESTART_APP"},
	132: {"ROBUST_CHANNEL_CE16_ERROR", "CE16: Unknown Error", "RESTART_APP"},
	133: {"ROBUST_CHANNEL_CE17_ERROR", "CE17: Unknown Error", "RESTART_APP"},
	134: {"ROBUST_CHANNEL_CE18_ERROR", "CE18: Unknown Error", "RESTART_APP"},
	135: {"ROBUST_CHANNEL_CE19_ERROR", "CE19: Unknown Error", "RESTART_APP"},
	136: {"ALI_TRAINING_FAIL", "Link Training Failed", "RESET_GPU"},
	137: {"NVLINK_PRIV_ERR", "NVLink Privilege Error", "IGNORE"},
	139: {"ROBUST_CHANNEL_OFA1_ERROR", "OFA1 Error", "RESTART_APP"},
	140: {"UNRECOVERABLE_ECC_ERROR_ESCAPE", "ECC Unrecovered Error", "RESET_GPU"},
	141: {"ROBUST_CHANNEL_FAST_PATH_ERROR", "CUDA Fast Path Error", "IGNORE"},
	142: {"ROBUST_CHANNEL_NVENC3_ERROR", "NVENC3 Error", "CONTACT_SUPPORT"},
	143: {"GPU_INIT_ERROR", "GPU Initialization Error", "RESET_GPU"},
	144: {"NVLINK_SAW_ERROR", "NVLINK: SAW Error", "WORKFLOW_NVLINK5_ERR"},
	145: {"NVLINK_RLW_ERROR", "NVLINK: RLW Error", "WORKFLOW_NVLINK5_ERR"},
	146: {"NVLINK_TLW_ERROR", "NVLINK: TLW Error", "WORKFLOW_NVLINK5_ERR"},
	147: {"NVLINK_TREX_ERROR", "NVLINK: TREX Error", "WORKFLOW_NVLINK5_ERR"},
	148: {"NVLINK_NVLPW_CTRL_ERROR", "NVLINK: NVLPW_CTRL Error", "WORKFLOW_NVLINK5_ERR"},
	149: {"NVLINK_NETIR_ERROR", "NVLINK: NETIR Error", "WORKFLOW_NVLINK5_ERR"},
	150: {"NVLINK_MSE_ERROR", "NVLINK: MSE Error", "WORKFLOW_NVLINK5_ERR"},
	151: {"ROBUST_CHANNEL_KEY_ROTATION_ERROR", "Key rotation Error", "RESTART_VM"},
	152: {"ROBUST_CHANNEL_DLA_SMMU_ERROR", "DLA SMMU Error", "IGNORE"},
	153: {"ROBUST_CHANNEL_DLA_TIMEOUT", "DLA timeout Error", "IGNORE"},
	154: {"GPU_RECOVERY_ACTION_CHANGED", "GPU Recovery Action Changed", "XID_154"},
	155: {"NVLINK_SW_DEFINED_ERROR", "NVLINK: SW Defined Error", "RESET_GPU"},
	156: {"RESOURCE_RETIREMENT_EVENT", "Resource Retirement Event", "RESET_GPU"},
	157: {"RESOURCE_RETIREMENT_FAILURE", "Resource Retirement Failure", "IGNORE"},
	158: {"GPU_FATAL_TIMEOUT", "GPU Fatal Timeout", "RESET_GPU"},
	159: {"ROBUST_CHANNEL_CHI_NON_DATA_ERROR", "CHI Non-Data Error", "CHECK_UVM"},
	160: {"CHANNEL_RETIREMENT_EVENT", "Channel Retirement Event", "IGNORE"},
	161: {"CHANNEL_RETIREMENT_FAILURE", "Channel Retirement Failure", "IGNORE"},
	162: {"PSHC_REENGAGED", "Power Smoothing HW Circuitry capability reengaged", ""},
	163: {"PSHC_DISENGAGED", "Power Smoothing HW Circuitry capability disengaged", ""},
	164: {"PSHC_LOW_LIFETIME", "Power Smoothing HW Circuitry low lifetime reached", ""},
	165: {"PSHC_ZERO_LIFETIME", "Power Smoothing HW Circuitry lifetime exhausted", ""},
	166: {"NVLINK_SECURE_CRYPTO_ERR", "CC traffic seen prior to link properly being configured for encrypted traffic", ""},
	167: {"PCIE_FATAL_TIMEOUT", "PCIE_FATAL_TIMEOUT", ""},
	168: {"REDUCED_GPU_MEMORY_CAPACITY", "Errors found in WPR (write protected region)", ""},
	169: {"SEC2_HALT_ERROR", "Internal micro-controller halt", ""},
	170: {"NVLINK_SECURE_OTHER", "Interrupt seen in CC mode", ""},
	171: {"UNCORRECTABLE_DRAM_ERROR", "Additional to Xid 48 providing more details on particulars of fault to differentiate DRAM/SRAM", ""},
	172: {"UNCORRECTABLE_SRAM_ERROR", "Additional to Xid 48 providing more details on particulars of fault to differentiate DRAM/SRAM", ""},
}
